export default {
  arrBg: [
    "blue50",
    "darkblue50",
    "darkblue30",
    "green50",
    "grey40",
    "red50",
    "yellow50",
    "blue60",
    "green60",
    "grey70",
    "red60",
    "yellow60",
    "blue70",
    "darkblue70",
    "green70",
    "grey80",
    "red70",
    "yellow70",
  ],
  arrStuff: ["earings", "flower", "glasses", "headphone"],
  arrEars: ["default", "tilt-backward", "tilt-forward"],
  arrEyes: ["angry", "default", "naughty", "panda", "smart", "star"],
  arrHair: ["bang", "curls", "default", "elegant", "fancy", "quiff", "short"],
  arrLeg: [
    "bubble-tea",
    "cookie",
    "default",
    "game-console",
    "tilt-backward",
    "tilt-forward",
  ],
  arrMouth: ["astonished", "default", "eating", "laugh", "tongue"],
  arrNeck: ["default", "bend-backward", "bend-forward", "thick"],
};
